parameters:
- name: environments
  type: object
  default: ['d']
- name: should_dependency_check
  type: boolean
  default: false

trigger: 
  branches:
    include:
      - develop
      - feature/**
pr: none

pool:
  vmImage: "ubuntu-latest"

stages:
- template: /devops/pipelines/templates/ci-template.yml
  parameters:
    environments: ${{ parameters.environments }}
    should_dependency_check: ${{ parameters.should_dependency_check }}