variables:
  envDevOpsServiceConnection: devops-arm-d
  sqlDbSolution: denicestbanksqldb  
  envRegionCode: swc
  envRegionName: swedencentral

  sqlUsername: sql_admin
  dotnetSdkVersion: 7.0
  portalApiSolution: denicestbankportal