CREATE TABLE Person
(
    Id       UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FullName NVARCHAR(100) NOT NULL,
    email    NVARCHAR(100) UNIQUE NOT NULL,
    roleId   INT FOREIGN KEY REFERENCES Role (Id),
    ssn      NVARCHAR(11) UNIQUE NOT NULL
);